version: '3.10'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - New_Project/docker.env
    volumes:
      - .:/srv/app
    command: python manage.py runserver


